.\" Manpage for wclock
.\" Contact (kvngncrlsn@gmail.com) to correct errors or typos.
.TH man 1 "09 July 2021" "0.1.0" "wclock man page"
.SH NAME
wclock \- check times from around the world in a terminal emulator or tty 
.SH SYNOPSIS
wclock [-t|--there DATETIME -b] SEARCH [-b|--break SEARCH] ...
wclock [-l|--local DATETIME -b] SEARCH [-b|--break SEARCH] ...
.SH QUERY MODE
wclock -q|--query [DIRECTORY]
.SH DESCRIPTION
wclock is a shell script for checking times from any time zone while using a tty or terminal emulator. It interfaces with the time zone data in /usr/share/zoneinfo to retrieve the correct time zone, and passes this time zone to date(1) to report world times matching a search term. 

Oustide of query mode, the search term can be either a city or a country; wclock will first check SHAREDIR/wclock/extras for an exact match. This file contains a selection of cities and metro areas with a population of over 400,000, as well as countries with ISO codes in the tz database. Nearly 1400 additional cities and almost every country are searchable in this manner.

If an exact match is not found, defined time zones are searched. If the search term has still not been found, SHAREDIR/wclock/extras is checked once more for non-exact matches.

To fetch times for multiple locations, place -b (--break) between the individual search terms. -b has no effect before the first search term, unless -t (--there) or -l (--local) is used.

--there and --local are used to pass a DATETIME parameter to date(1):

\t --there: Find your local time at DATETIME in the SEARCH time zone.

\t --local: Find the time in SEARCH at DATETIME in your local time zone.

Because wclock will add time zone information to DATETIME, only the time (and day, if desired) are needed. For more information, see "DATETIME" below; date(1) is another useful reference. When using --there and --local, any following search arguments will have the corresponding DATETIME check, until the opposite flag is used:

\t wclock -t 10:00 next Wed -b glasgow -b kiev
"there" checks for Glasgow and Kiev.

\t wclock glasgow -t 10:00 next Wed -b kiev
"there" check for Kiev only.

\t wclock -l 16:00 -b glasgow -t 10:00 next Wed -b kiev
"local" check for Glasgow; "there" check for Kiev.

In query mode (-q or --query), wclock will show defined time zones asociated with a directory under /usr/share/zoneinfo (if DIRECTORY is given). If DIRECTORY is not given, it will show a list of directories that contain time zone data. 
.SH OPTIONS
SEARCH - A search term for the desired time; this can be a time zone as named in /usr/share/zoneinfo, a city included in SHAREDIR/wclock/extras, or a country.

-q|--query - With a search term, display all time zones associated with that directory in /usr/share/zoneinfo. Without a search term, show a list of directories in /usr/share/zoneinfo. Incompatible with -b, -t and -l.

-b|--break - For multiple searches, use -b between each search term. Incompatible with -q.

-t|--there - Find your local time when it is DATETIME in SEARCH. Incompatible with -q.

-l|--local - Find the time in SEARCH when it is DATETIME in your local time. Incompatible with -q.

DATETIME - A future or past time to check. This parameter is passed to date(1); wclock handles setting TZ and passing the local time offset automatically. Input should not be quoted. In general, the preferred syntax is TIME [DAY], where DAY can be a date, a day of the week, or a relative term (e.g., "tomorrow."). As an example,

\t wclock -t 17:00 2021/07/16 -b minneapolis

shows the local time when it is 17:00 in Minneapolis on July 16th.

\t wclock -l 12:00 tomorrow -b luxembourg

shows the time in Luxembourg at 12:00 local time, tomorrow.

When passing DATETIME with --local or --there, all following search arguments will have the check applied until the opposite check is used.

-h|--help - Display the help menu.
.SH SEE ALSO
date(1)
.SH BUGS
To report bugs, request additional entries in SHAREDIR/wclock/extras, etc., email the author directly or open an issue at wclock's home on GitHub: https://github.com/pghvlaans/wclock.
.SH AUTHOR
K. Eugene Carlson (kvngncrlsn@gmail.com)
