#!/bin/sh
#
# validate-timesetter
#
# Copyright (c) 2021-2022 K. Eugene Carlson  Tsukuba, Japan
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#
# A sanity check for a well-formed TIMESETTER parameter, if any. Runs at
# installation.
#

[ -z "$TIMESETTER" ] && exit
if [ ! -f "$TIMESETTER" ]; then
  echo
  echo "$TIMESETTER" does not exist. To continue the installation anyway,
  echo enter "y". To exit, enter any other character.
  echo
  unset INPUT
  read -r INPUT && [ "$INPUT" != y ] && echo && exit 1
  echo
  exit
fi

unset CHECKER
unset CHECKER2
unset NEWZONEINFO

getzoneinfo (){
if [ -n "$ZONEINFO" ]; then
  ./validate-zoneinfo "$ZONEINFO"
  [ -z "$CHECKZONEINFO" ] && NEWZONEINFO="$ZONEINFO" && return
fi
for x in /usr/share/zoneinfo-leaps \
         /usr/share/zoneinfo \
         /usr/local/share/zoneinfo-leaps \
         /usr/local/share/zoneinfo \
         /etc/zoneinfo-leaps \
         /etc/zoneinfo; do
  if [ -d "$x" ]; then
    ./validate-zoneinfo "$x"
    [ -z "$CHECKZONEINFO" ] && NEWZONEINFO="$x" && return
  fi
done
}

unset PWD
PWD="$(pwd)"
cd "$(dirname "$TIMESETTER")"
CHECKER="$(file -b "$(readlink -e "$TIMESETTER")" | grep timezone)"
[ -n "$CHECKER" ] && cd "$PWD" && exit
cd "$PWD"
if [ ! -h "$TIMESETTER" ]; then
  getzoneinfo
  [ ! -d "$NEWZONEINFO" ] && exit
  CHECKER="$(cat "$TIMESETTER")"
  CHECKER2="$(find "$NEWZONEINFO" -type f,l | grep -i -m 1 "$CHECKER")"
  if [ -z "$CHECKER2" ]; then
    echo
    echo "$TIMESETTER" does not appear to point to a valid time zone setting
    echo file or symlink. To continue the installation anyway, enter "y". To
    echo exit, enter any other character.
    echo
    unset INPUT
    read -r INPUT && [ "$INPUT" != "y" ] && echo && exit 1
    echo
    exit
  fi
fi
