#!/bin/sh
#
# wclock
#
# Copyright (c) 2021 K. Eugene Carlson  Tsukuba, Japan
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#
# A simple world clock script for terminal emulator and tty use.
#

unset QUERY
unset city
unset zone
unset SHAREDIR
unset SUFFIX
unset SLASHES
unset THERE
unset HERE
unset NOECHO
unset WRITTEN
unset FLAGS

# Although both posix and right should be available in Linux installations, one
# or both may be absent in a *BSD installation.
if [ -d "/usr/share/zoneinfo/posix" ]; then
	SUFFIX="posix/"
elif [ -d "/usr/share/zoneinfo/right" ]; then
	SUFFIX="right/"
fi

SLASHES="$(echo "/usr/share/zoneinfo/$SUFFIX" | tr -cd '/' | wc -c)"
SLASHES=$((SLASHES + 1))

comparemethod (){
if [ "$THERE" = "yes" ]; then
	ENTRY="--date=TZ=\""$place"\" $FLAGS"
	echo '	'$(date "$ENTRY") here
	echo '	'"$(TZ="$place" date "$ENTRY")" in "$headup"
	echo
	NOECHO=yes
fi
		
if [ "$HERE" = "yes" ]; then
	ENTRY="--date=$FLAGS"
	[ "$WRITTEN" != "yes" ] && echo '	'"$(date "$ENTRY")" here
	echo '	'$(TZ="$place" date "$ENTRY") in "$headup"
	WRITTEN=yes
fi
}

main (){
# "make install" will fill this part in with SHAREDIR. SHAREDIR is PREFIX/share 
# by default.
SHAREDIR=

ZONETEMP="$HOME/.zonetemp"
EXTRAS="$SHAREDIR"/wclock/extras

[ "$QUERY" != "yes" ] && [ -z "$city" ] && echo && echo '	'No search arguments. && wclock --help && exit
# A blank query mode call displays available directories.
[ "$QUERY" = "yes" ] && [ -z "$city" ] && find /usr/share/zoneinfo/"$SUFFIX" -type d | cut -d'/' -f"$SLASHES"- | less && exit

echo

unset TIMESTAMP

if [ -f "$ZONETEMP" ] || [ -d "$ZONETEMP" ] || [ -h "$ZONETEMP" ]; then
	TIMESTAMP="$(date +%s)"
	mv "$ZONETEMP" "$ZONETEMP-$TIMESTAMP"
fi

# If there's an exact match in the extras file, go with that.
zone="$(grep -i "^$city	" "$SHAREDIR"/wclock/extras)"
[ -n "$zone" ] && echo "$zone" > "$ZONETEMP"
unset WRITTEN
[ -f "$ZONETEMP" ] && while read -r line; do
	X=$(wc -l "$ZONETEMP")
	unset name
	unset place
	name="$(echo "$line" | cut -d'	' -f1)"
	place="$(echo "$line" | cut -d'	' -f2-)"

	if [ ! "$X" = "1 $ZONETEMP" ]; then
		headup="$place"
	else
		headup="$name ($place)"
	fi

	[ -z "$FLAGS" ] && echo '	'"$(TZ="$place" date)"'	'"$name" \("$place"\)
	[ -n "$FLAGS" ] && comparemethod
done < "$ZONETEMP"

# Otherwise, search for a match among the named time zones.
unset zone
[ ! -f "$ZONETEMP" ] && zone="$(find /usr/share/zoneinfo/"$SUFFIX"* -type f,l | grep -i "$city" | cut -d'/' -f"$SLASHES"-)"

[ -n "$zone" ] && echo "$zone" > "$ZONETEMP"

if [ -n "$zone" ] && [ -f "$ZONETEMP" ]; then
	while read -r place; do
		headup="$place"
	
		[ -z "$FLAGS" ] && echo '	'"$(TZ="$place" date)"'	'"$place"
		[ -n "$FLAGS" ] && comparemethod
	done < "$ZONETEMP"
elif [ -z "$zone" ] && [ ! -f "$ZONETEMP" ]; then
	# If no match is available, resort to the "extras" list, which has
	# countries and other cities.
	unset zones
	zones="$(grep -i "$city" "$EXTRAS")"
	[ -n "$zones" ] && echo "$zones" >> "$ZONETEMP"
	[ -f "$ZONETEMP" ] && while read -r line; do
		X=$(wc -l "$ZONETEMP")
		unset name
		unset place
		name="$(echo "$line" | cut -d'	' -f1)"
		place="$(echo "$line" | cut -d'	' -f2-)"
	
		if [ ! "$X" = "1 $ZONETEMP" ]; then
			headup="$place"
		else
			headup="$name ($place)"
		fi
	
		[ -z "$FLAGS" ] && echo '	'"$(TZ="$place" date)"'	'"$name" \("$place"\)
		[ -n "$FLAGS" ] && comparemethod
	done < "$ZONETEMP"
	# Bad luck; nothing was found.
	[ ! -f "$ZONETEMP" ] && echo The search term revealed no time zones.
fi

# Cleaning up.
rm -f "$ZONETEMP"
if [ -f "$ZONETEMP-$TIMESTAMP" ] || [ -d "$ZONETEMP-$TIMESTAMP" ] || [ -h "$ZONETEMP-$TIMESTAMP" ]; then
	mv "$ZONETEMP-$TIMESTAMP" "$ZONETEMP"
fi
}

for arg in "$@"; do
	case "$arg" in 
		# Use query mode to help find genuine time zone names.
		-h|--help)
		echo
		echo wclock - Retrieve world times based on a search term.
		echo
		echo SYNTAX:
		echo wclock [-t\|--there DATETIME -b] SEARCH [-b\|--break SEARCH] ...
		echo wclock [-l\|--local DATETIME -b] SEARCH [-b\|--break SEARCH] ...
		echo
		echo QUERY MODE:
		echo wclock -q\|--query [DIRECTORY]
		echo
		echo OPTIONS:
		echo -q\|--query - With DIRECTORY, display defined time zones in the specified time zone directory.
		echo '	'Without DIRECTORY, display all directories under /usr/share/zoneinfo with time zone data.
		echo '	'Incompatible with -b.
		echo
		echo -b\|--break - Enter between search terms to retrieve multiple time zones.
		echo
		echo -t\--there - Find your local time when it is DATETIME in SEARCH.
		echo
		echo -l\--local - Find the time in SEARCH when it is DATETIME in your time.
		echo
		echo SEARCH - A city or country. Available cities include the namesakes of all defined time zones,
		echo '	'as well as a selection of other areas with a population of 400,000 or more.
		echo
		echo DATETIME - A past or future date and/or time to check. wclock will add any required time
		echo '	'zone information automatically. In general, the preferred syntax is "TIME DAY". DAY can
		echo '	'be a day of the week, full date, etc. For example,
		echo
		echo '		'wclock --there 16:00 next Thu -b washington
		echo '		'wclock --local 12:00 2021/09/26 -b india
		echo
		echo '	'See date\(1\) for more information about formatting.
		echo
		echo A man page can be found at wclock\(1\).
		echo
		exit
		;;
		-q|--query)
		QUERY=yes		
		;;
		-b|--break)
		[ -n "$city" ] && main
		unset GETFLAG
		unset city
		;;
		-t|--there)
		unset HERE	
		GETFLAG=yes
		unset FLAGS
		THERE=yes
		;;
		-l|--local)
		unset THERE
		GETFLAG=yes
		unset FLAGS
		HERE=yes
		;;
		*)
		# Query with another argument
		if [ "$QUERY" = "yes" ]; then
			find /usr/share/zoneinfo/"$SUFFIX" -type f,l | grep -i "$arg" | cut -d'/' -f6- | cut -d'/' -f2- | sort | less
			exit
		elif [ "$GETFLAG" = "yes" ]; then
			if [ -z "$FLAGS" ] && [ "$HERE" = "yes" ]; then 
				FLAGS="$arg"\ "$(date +%z)"
				DISPFLAGS="$arg"
			elif [ -z "$FLAGS" ] && [ "$THERE" = "yes" ]; then
				FLAGS="$arg"
				DISPFLAGS="$arg"
			else
				FLAGS="$FLAGS"\ "$arg"
				DISPFLAGS="$DISPFLAGS"\ "$arg"
			fi
		else
			# Replace spaces with underscores
			[ -n "$city" ] && city="$city"_"$arg"
			[ -z "$city" ] && city="$arg"
		fi
		;;
	esac
done
main
[ "$NOECHO" != "yes" ] && echo
