#!/bin/sh
#
# validate-zoneinfo
#
# Copyright (c) 2021 K. Eugene Carlson  Tsukuba, Japan
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#
# Sanity check for a well-formed zoneinfo directory. Runs at installation and
# during the main loop.
#
# "$1" is the full path to the zoneinfo directory.
# "$2" is an indicator that the script was called from Makefile.
#

[ -z "$1" ] || [ "$1" = "MAKEFILE" ] && exit

unset CHECKZONEINFO

if 	[ ! -f "$1"/America/Sao_Paulo ] || \
	[ ! -f "$1"/Europe/Moscow ] || \
	[ ! -f "$1"/Africa/Cairo ] || \
	[ ! -f "$1"/Asia/Tokyo ] || \
	[ ! -f "$1"/Pacific/Auckland ] || \
	[ ! -f "$1"/Australia/Sydney ] || \
	[ ! -f "$1"/Atlantic/Canary ] || \
	[ ! -f "$1"/Indian/Reunion ] || \
	[ ! -f "$1"/Antarctica/McMurdo ] || \
	[ ! -f "$1"/Etc/GMT ]; then
	case "$2" in
		MAKEFILE)
		echo
		echo "$1" does not appear to be a well-formed zoneinfo directory. To continue
		echo the installation anyway, enter "y". To exit, enter any other character.
		echo
		unset INPUT
		read -r INPUT && [ "$INPUT" != "y" ] && echo && exit 1
		echo
		;;
		*)
		CHECKZONEINFO=yes
		;;
	esac
fi
